#lang ivy1.7

include node
include network

type value
type id

instance node_instance : node(value, id)
instance network_instance : network(node_instance, value)

# IVy will play with these two actions
# and see if any invariants ever get violated.
export network_instance.enqueue_vote
export network_instance.deliver_vote

# I'm still not quite sure how the isolate stuff works.
# TODO: Read more about it.
isolate iso_network = network

extract iso_impl = network
